#!/usr/bin/env bash

# List of servers to SSH into
SERVERS=("niagara" "graham" "narval" "beluga" "cedar")

# Start a new tmux session
SESSION_NAME="multi-ssh"
tmux new-session -d -s "$SESSION_NAME"

# Create a new window (if you want to keep the first window clean)
tmux new-window -t "$SESSION_NAME" -n "SSH_Servers"

# SSH into each server in a new panel
for i in "${!SERVERS[@]}"; do
    SERVER="${SERVERS[$i]}"
    CURRENT_PORT=$((1000 + i))  # Increment the port number

    if [ "$i" -eq 0 ]; then
        # First server, use the default pane
        tmux send-keys -t "$SESSION_NAME:SSH_Servers" "ssh -L ${CURRENT_PORT}:localhost:8001 $SERVER" C-m
    else
        # Split the pane and SSH into the server
        tmux split-window -t "$SESSION_NAME:SSH_Servers" "ssh -L ${CURRENT_PORT}:localhost:8001 $SERVER"
        tmux select-layout -t "$SESSION_NAME:SSH_Servers" tiled
    fi


    # Wait for 2 seconds, then send "1" to all panes
    sleep 1
    tmux send-keys -t "$SESSION_NAME:SSH_Servers" "1" C-m
done

# Attach to the tmux session
tmux attach-session -t "$SESSION_NAME"
